spring.config.activate.on-profile=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/realestatecrm?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${CRM_DB_USERNAME:root}
spring.datasource.password=${CRM_DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
